### ISSUE TITLE
Ogamed vs library 

### ISSUE THREAD

**Issue by eperdeme** [alaingilbert/ogame#10]
Hello, just a quick question.

Has the Ogamed service only got a limited subset of the main library resources? So for example it currently it cannot call 'GetEspionageReport' resources until they are added to https://github.com/alaingilbert/ogame/blob/master/cmd/ogamed/main.go#L74 ?

**Comment by alaingilbert** [comment]
That's right.
The thing is, I use the library a lot, and improve it all the time, and I don't really use the service.
So it gets a little bit neglected. But it would be very easy to add any missing feature.

**Comment by eperdeme** [comment]
Ok that's all I needed to know. Was just making sure I was not missing something that would allow me dynamically call the libs underneath via the HTTP interface.
