### ISSUE TITLE
captcha required?

### ISSUE THREAD

**Issue by cookie050** [alaingilbert/ogame#112]

**Comment by alaingilbert** [comment]
It means you have to solve a captcha to complete the login.
You can use telegram to solve it -> https://github.com/alaingil
bert/ogame/blob/56e4797fb2510942aa94381e438d6274723f135d/ogame.go#L996
Or any other strategy that you might want to implement.

![Screen Shot 2022-08-15 at 4 44 23 PM](https://user-images.githubusercontent.com/886683/184751880-342153c6-81f4-4fb5-b37d-a365c01ba35e.png)
