### ISSUE TITLE
Expeditions fleet slots

### ISSUE THREAD

**Issue by eperdeme** [alaingilbert/ogame#16]
Hello,

I noticed you merged in a few days/week ago the code to be able to do expeditions.
Is this code working for you when calling GetSlots?

I've given it a quick go and this was my result;
```
   slots := bot.GetSlots()
	 fmt.Println(slots)
```
{14 14 0 0}

It correctly shows my 14/14 fleet slots in use, but the expedition slots always shows 0/0, the UI shows 1 used of total 3.

**Comment by alaingilbert** [comment]
Seems to work fine for me. What's the server language on which you play ?

**Comment by eperdeme** [comment]
EN.

**Comment by alaingilbert** [comment]
Are you on discord ?
#2967 agilbert

would be easier to debug.

**Comment by alaingilbert** [comment]
Fixed here https://github.com/alaingilbert/ogame/commit/050276a180c72269256cb65f695e249121984641

**Comment by eperdeme** [comment]
Looks fixed, tested and works. Thank you.
