### ISSUE TITLE
Help: Can someone help me to use the fleetBuilder Factory?

### ISSUE THREAD

**Issue by Kane67** [alaingilbert/ogame#18]
Hello All,

First I would like to thank you for your work and to provide such a great library for OGame! This is amazing huge and admirable! Thank you very much for that!

I am a GO novice and totally stuck in the learning process. I am actually have difficulties to understand the GO Code and study your library.

May I ask someone to give me an example how to call and use the fleetBuilder and FleetBuilderFactory and setup a fleet and use sendNow function?

This would be very very helpful! 

I hope this isn't too much to ask.

Thank you all for any help!

here is my progress
Would the usage be correct?

```
package main

import (
	"log"

	"github.com/alaingilbert/ogame"

	_ "fmt" // no more error
)

func main() {
	log.SetFlags(log.Ltime | log.Lshortfile)
	params := ogame.Params{
		Universe:  "Universename",
		Username:  "email@isp.domain",
		Password:  "Password",
		Lang:      "en",
		AutoLogin: true,
		//Proxy:     "http://192.168.1.1:8123/",
	}

	bot, err := ogame.NewWithParams(params)
	if err != nil {
		log.Fatal(err)
	}


	fb := ogame.NewFleetBuilderFactory(bot)
	fleet := fb.NewFleet()
	fleet.SetOrigin(35993262)
	fleet.SetDestination(36072196)
	fleet.SetSpeed(1)
	fleet.SetAllResources()
	fleet.SetMission(4)
	fleet.SetAllShips()
	//fleet.SetRecallIn(300)
	fleet.SendNow()
}
```

**Comment by Kane67** [comment]
This is what I have already.

```
package main

import (
	"log"

	"github.com/alaingilbert/ogame"

	_ "fmt" // no more error
)

func main() {
	log.SetFlags(log.Ltime | log.Lshortfile)
	params := ogame.Params{
		Universe:  "Universename",
		Username:  "email@isp.domain",
		Password:  "Password",
		Lang:      "en",
		AutoLogin: true,
		//Proxy:     "http://192.168.1.1:8123/",
	}

	bot, err := ogame.NewWithParams(params)
	if err != nil {
		log.Fatal(err)
	}

	fb := ogame.NewFleetBuilderFactory(bot)
}
```

**Comment by flashover** [comment]
Hi Kane,

I've not worked with the FleetBuilder, but by looking at the code you can choose:

- use SetAllShips : it will query the planet and it will then select all ships for you : https://github.com/alaingilbert/ogame/blob/master/fleetBuilder.go#L152
- use the AddShips function where you need to provide ShipIDs. You can find those in https://github.com/alaingilbert/ogame/blob/master/constants.go#L127 

I see you're calling the fleet.SendNow() function, but looking at it's source code it gives two returns:

`
func (f *FleetBuilder) SendNow() (Fleet, error) {
`

https://github.com/alaingilbert/ogame/blob/master/fleetBuilder.go#L147

So I think you'd need something in this direction:

`
mission, error = fleet.SendNow()

if error != nil {
	log.Print("Unable to send the fleet")
} else {
	log.Print("Successfully sent ships: ", mission)
}
`

**Comment by alaingilbert** [comment]
The following code works well for me:
```go
package main

import (
	"fmt"
	"github.com/alaingilbert/ogame"
)

func main() {
	params := ogame.Params{
		Universe:  "Universename",
		Username:  "email@isp.domain",
		Password:  "password",
		Lang:      "en",
		AutoLogin: true,
	}
	bot, err := ogame.NewWithParams(params)
	if err != nil {
		panic(err)
	}

	fb := ogame.NewFleetBuilder(bot)
	fb.SetOrigin("4:215:5")
	fb.SetDestination("4:107:2")
	fb.SetSpeed(ogame.TenPercent)
	fb.SetAllResources()
	fb.SetMission(ogame.Transport)
	fb.SetAllShips()
	fleet, err := fb.SendNow()

	fmt.Println(fleet, err)
}
```

**Comment by Kane67** [comment]
Thank very to all for your Answer!

Good hint that I can call NewFleetBuilder directly.

The error and fleet object values are very useful and yes I use them for error handling. I have a small function which send the fleet which is handling the error and retry sending if fails.

I have a lot of questions but I try to figure things out myself before bothering you with rookieness next time.

Have a nice day.
