### ISSUE TITLE
Make File "cmd/scripts/web/public/..."

### ISSUE THREAD

**Issue by Kane67** [alaingilbert/ogame#20]
May I ask you to get "cmd/scripts/web/public" etc?

```
go-bindata -pkg bindata -o cmd/scripts/bindata/bindata.go -prefix "cmd/scripts/web/public/" cmd/scripts/web/public/...
bindata: Failed to stat input path 'cmd/scripts/web/public': lstat cmd/scripts/web/public: no such file or directory
Makefile:20: recipe for target 'bindata-prod' failed
make: *** [bindata-prod] Error 1

```

**Comment by TuxLinus** [comment]
I don't think he will publish this!

**Comment by alaingilbert** [comment]
I think I just copied/pasted the Makefile from another project.
The `bindata` just have no purpose in this project...

**Comment by Kane67** [comment]
Thanks for information! Best wishes!
Do you have another project with a user interface then?

**Comment by alaingilbert** [comment]
I heard that this project has a pretty good user interface http://ogame.ninja
(totally not maintained by me)

**Comment by Kane67** [comment]
Thanks for the info I will check it out. But anyway I would love to get more experienced and build my own public interface. I want to share it not making money with it because I don't need more money. XD
