### ISSUE TITLE
[Solved] func (b *OGame) GetFleetsFromEventList() []Fleet -> Returns empty Fleet Array

### ISSUE THREAD

**Issue by Kane67** [alaingilbert/ogame#22]
This function returns just an empty Fleet Array, while the "func (b *OGame) GetFleets() ([]Fleet, Slots)" is returning the right Slots and complete Fleet Array. Or is GetFleetsFromEventList() only for attacking fleets and not for my own fleet?

**Comment by flashover** [comment]
Hi Kane,

I'm using the library through the API and I know that a HTTP-GET to "/bot/fleets" returns a list with your own fleets, but not any incoming attacks.

If you want the incoming attacks you can perform the HTTP-GET to "/bot/attacks". Normally that list is quite empty. I hooked it up to a Telegram bot and it sends a message to my phone with the whole JSON output when the number of items in that list is bigger than 1.

Can you take a look there to see which library functions are called by the API?

Hope this helps!

**Comment by Kane67** [comment]
I dont use "cmd/ogamed" I use my own GO Program which call the GetFleetsFromEventList() Function and the Output is same as the GetFleets() Function except the Slots. I was looking at the function code and I can not find any error. I have moving fleets and GetFleets() shows me anything and the EventList Function is empty.

Maybe I just misunderstood the Function usage?

:+1:  Thank you for the hint about the Attack Function, but I already knew it! But thank you anyway!!! :+1:

**Comment by apg258** [comment]
> This function returns just an empty Fleet Array, while the "func (b *OGame) GetFleets() ([]Fleet, Slots)" is returning the right Slots and complete Fleet Array. Or is GetFleetsFromEventList() only for attacking fleets and not for my own fleet?

It does seem like it is a deprecated function considering the test to its root function is commented out. I'd stick to GetFleets().
```go
func TestExtractFleetsFromEventList(t *testing.T) {
	//pageHTMLBytes, _ := ioutil.ReadFile("samples/eventlist_test.html")
	//fleets := ExtractFleetsFromEventList(pageHTMLBytes)
	//assert.Equal(t, 4, len(fleets))
}
```

**Comment by TuxLinus** [comment]
There is a bug in File "ogame.go"
You need to request a page and this is eventList

```
func (b *OGame) getFleetsFromEventList() []Fleet {
	pageHTML, _ := b.getPageContent(url.Values{"page": {"eventList"}, "ajax": {"1"}})
	return ExtractFleetsFromEventList(pageHTML)
}
```


WRONG Code:
```
func (b *OGame) getFleetsFromEventList() []Fleet {
	pageHTML, _ := b.getPageContent(url.Values{"eventList": {"movement"}, "ajax": {"1"}})
	return ExtractFleetsFromEventList(pageHTML)
}
```

**Comment by Kane67** [comment]
Great this helped! I fixed it now! Thank you very much!

**Comment by Kane67** [comment]
# #
