### ISSUE TITLE
cargo value has been changed.

### ISSUE THREAD

**Issue by jc01rho** [alaingilbert/ogame#23]
https://board.en.ogame.gameforge.com/index.php/Thread/806564-Game-version-6-8-5-soon%E2%84%A2/?s=f13d284b8ded8d44566e37ed90303eb7f28a0acf

Changelog:
[Feature] Hyperspace technology adds now 2% of cargo capacity to all ships per level. It starts from level 1.

!! not the engine, but tech. :)

**Comment by alaingilbert** [comment]
Yup, I saw that. We'll make a fix for this soon.

**Comment by Kane67** [comment]
Super info! Thank you!

**Comment by alaingilbert** [comment]
Which server are you playing on ?
It seems to be live on all the servers that I play on.
(en, es, dk)

**Comment by Kane67** [comment]
I correct its live! Sorry!

**Comment by apg258** [comment]
Implemented in https://github.com/alaingilbert/ogame/pull/24.
