### ISSUE TITLE
connectChat reveals your IP Adress if you set a proxy for the bot!

### ISSUE THREAD

**Issue by TuxLinus** [alaingilbert/ogame#26]
First shot for a Solution:

in the function there are two parts who reveals the IP

**http.NewRequest** and **websocket.Dial**

```
proxyUrl, err := url.Parse("http://proxyIp:proxyPort")
myClient := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyUrl)}}
```

```
/*
You could also modify the default transport used by the "net/http" package. This would affect your entire program (including the default HTTP client).
*/

proxyUrl, err := url.Parse("http://proxyIp:proxyPort")
http.DefaultTransport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
```

```
 var d = websocket.Dialer{
     Proxy: http.ProxyURL(&url.URL{
          Scheme: "http", // or "https" depending on your proxy
          Host: "ipaddress:port" ,
          Path: "/",
    }
 } 
```

**Comment by alaingilbert** [comment]
https://github.com/alaingilbert/ogame/blob/master/ogame.go#L620
That is the only call that needs to be proxied.
It's the only http call that they monitor in their admin tools.

**Comment by Kane67** [comment]
Okay @TuxLinus I would like to say that the http has already set an Transport Proxy in the api ogame.go any further requests are using the Proxy Server!

about the Websocket.Dialer yes it seems that it uses Direct Connection and dont uses the http Proxy.

**Comment by alaingilbert** [comment]
Admins don't see the IP of the websocket in their tool.
