### ISSUE TITLE
Update Hyperspace Cargo feature +5%

### ISSUE THREAD

**Issue by Kane67** [alaingilbert/ogame#27]
Dear community,
On Tuesday, 12th of March at 11:00 CET we will update the percentage of the Hyperspace cargo feature.
From 2% it will change into 5% in all opened servers.
Also, from now on, any new starting server will have the 5% already.

We hope you enjoy the change.

Your OGame Team.

**Comment by apg258** [comment]
Changed in https://github.com/alaingilbert/ogame/pull/25 which will be merged when changes go live.
