### ISSUE TITLE
github.com/Sirupsen/logrus case sentitive incompatibility

### ISSUE THREAD

**Issue by renatofl** [alaingilbert/ogame#3]
Hi alaingilbert,

I'm trying to use your ogame wrapper package with go-astilectron but I'm currently having some incompatibility problems (case senstive) with package imports.

This package: 

"github.com/Sirupsen/logrus" 

go-astilectron: 

"github.com/sirupsen/logrus"

I found some links where the maintainer recommends using all lower-case, you can found it here:
https://github.com/sirupsen/logrus/issues/570
https://github.com/sirupsen/logrus/issues/543

Could you change it ?

Thank you.

**Comment by alaingilbert** [comment]
Hello,
I changed the import https://github.com/alaingilbert/ogame/commit/6ece4ed7bc0270bb991e073f37f4d8fa8f790f2e

Let me know if you have any question or any other issue :)

**Comment by alaingilbert** [comment]
Turns out that I just removed logrus altogether. https://github.com/alaingilbert/ogame/commit/70a99438ef047432cfe4baf219c43f0d4add2e5c
