### ISSUE TITLE
New lobby update breaks the login process

### ISSUE THREAD

**Issue by apg258** [alaingilbert/ogame#31]
The new update:
https://board.en.ogame.gameforge.com/index.php/Thread/808737-OGame-accounts-are-becoming-a-Gameforge-account/

Seems to have broken the login process, at first glance it seems like the API is not accessible anymore, e.g. https://lobby-api.ogame.gameforge.com/users/me/accounts

**Comment by flashover** [comment]
If you change the Lobby URL Prefix you can use the bot again:

From:
`"https://lobby-api.ogame.gameforge.com/users/me/accounts"`

To:
`"https://lobby.ogame.gameforge.com/api/users/me/accounts"`

I will try to send a Pull Request for this.

**Comment by flashover** [comment]
https://github.com/alaingilbert/ogame/pull/32

**Comment by flashover** [comment]
I have to add that I already acknowledged the change to my account management today, so I'm not sure how the bot handles logins for people who have not yet tried to login using the old-school way without the bot.

**Comment by apg258** [comment]
Thanks @flashover. Changes to solve this issue merged in #32.
