### ISSUE TITLE
is OgameV7 fully compatible?

### ISSUE THREAD

**Issue by jc01rho** [alaingilbert/ogame#38]
[https://github.com/alaingilbert/ogame/commit/0aa06a3b7a9523a4549b6a995a2235f51fd53a7e](url)
just wondered that the commit log has V7 changes,
is this repo fully supports V7 ogames?

**Comment by alaingilbert** [comment]
Most features are v7 compatible. But I'm still in the transition phase, so probably not everything is working properly.
