### ISSUE TITLE
Errors V7 SendFleet : send with planet resources [SOLVED]

### ISSUE THREAD

**Issue by Nyura95** [alaingilbert/ogame#39]
Hello, i have a problem with the SendFleet (from a planet). 

When I create a new mission she's started good but she has no resources.

I print the payload from your function, but I don't see the problem

`map[acsValues:[] am203:[70] crystal:[1442229] deuterium:[1006935] galaxy:[1] holdingOrExpTime:[0] metal:[0] mission:[4] mode:[save] open_std:[1] position:[9] prioCrystal:[2] prioDeuterium:[3] prioMetal:[1] speed:[2] system:[497] template_id:[0] token:[6bf16455b25da112a7da02f142be448a] type:[1] union:[0] union2:[0]]`

Someone found the same problem?

**Comment by alaingilbert** [comment]
ogame v7.1 broke the feature to get resources.
You need to use the latest version 26.2.0

**Comment by Nyura95** [comment]
Hi @alaingilbert,  Thank you for your prompt reply <3.

I follow your updates every day.

I'm on your lasted commit: HEAD is now at dbd1d3f Merge branch 'release/26.2.0'
