### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mbaletic** [alaingilbert/ogame#40]
It would be nice to have a SOCKS proxy support for the ogamed.

**Comment by alaingilbert** [comment]
It should already be there https://github.com/alaingilbert/ogame/blob/master/cmd/ogamed/main.go#L75-L92

**Comment by mbaletic** [comment]
Thanks for the fast response, however, any of the new params I try passing in gives me 

https://prnt.sc/qav3iz

**Comment by mbaletic** [comment]
fixed
