### ISSUE TITLE
Play the game through localhost

### ISSUE THREAD

**Issue by mbaletic** [alaingilbert/ogame#42]
Pretty self explanatory,would be a nice feature to be able to play the game through ogamed on localhost.

**Comment by 0xE232FE** [comment]
done already: https://github.com/0xE232FE/ogame

**Comment by 0xE232FE** [comment]
You can look here: 	https://github.com/0xE232FE/ogame/blob/4cc6f72812474f402cc41c13b14a5c866442ca42/cmd/ogamed/main.go#L215

**Comment by 0xE232FE** [comment]
Done!
You can look here: 	https://github.com/0xE232FE/ogame/blob/4cc6f72812474f402cc41c13b14a5c866442ca42/cmd/ogamed/main.go#L215
