### ISSUE TITLE
"Destroyed Planets" in GalaxyInfos() return nil in the German Version

### ISSUE THREAD

**Issue by twdnhfr** [alaingilbert/ogame#57]
a destroyed planet will return nil in the german version when calling GalaxyInfos(), can we somehow fix this?

**Comment by alaingilbert** [comment]
Any suggestion what it should be ?

**Comment by twdnhfr** [comment]
It would be handy to have this as a Planet with a "destroyed" flag. Background is Im working on some logic to automate colonization. As far as I can see currently we cant detect colonizable Planets right?

btw: thanks a lot for the work here, I used pyogame back in the days and this is a great project to learn go :)
