### ISSUE TITLE
websocket for chat can fail

### ISSUE THREAD

**Issue by twdnhfr** [alaingilbert/ogame#58]
Hope this helps, it seems the websocket connection can fail

ERRO [ogame.go:816] chat eof: EOF
ERRO [ogame.go:781] failed to get socket.io token: Get https://sXXX-de.ogame.gameforge.com:20029/socket.io/1/?t=1579XXXXXXXXX: dial tcp 79.XXX.XX.XXX:20029: connect: connection refused
ERRO [ogame.go:781] failed to get socket.io token: Get https://sXXX-de.ogame.gameforge.com:20029/socket.io/1/?t=1579XXXXXXXXX: dial tcp 79.XXX.XX.XXX:20029: connect: connection refused
ERRO [ogame.go:781] failed to get socket.io token: Get https://sXXX-de.ogame.gameforge.com:20029/socket.io/1/?t=1579XXXXXXXXX: dial tcp 79.XXX.XX.XXX:20029: connect: connection refused
ERRO [ogame.go:781] failed to get socket.io token: Get https://sXXX-de.ogame.gameforge.com:20029/socket.io/1/?t=1579XXXXXXXXX: dial tcp 79.XXX.XX.XXX:20029: connect: connection refused
ERRO [ogame.go:781] failed to get socket.io token: Get https://sXXX-de.ogame.gameforge.com:20029/socket.io/1/?t=1579XXXXXXXXX: dial tcp 79.XXX.XX.XXX:20029: connect: connection refused
ERRO [ogame.go:844] Failed to connect to chat

**Comment by 0xE232FE** [comment]
I refer to issue #26 someone explained that the Websocket doesn't use the Proxy set in HTTP Client. So if you use a Proxy, the Websocket for Chat api is using the normal internet connection. So your IP-Address is leaked. **This Info is really importent for Multi Users.**

**Comment by mbaletic** [comment]
> I refer to issue #26 someone explained that the Websocket doesn't use the Proxy set in HTTP Client. So if you use a Proxy, the Websocket for Chat api is using the normal internet connection. So your IP-Address is leaked. **This Info is really importent for Multi Users.**
> 
> In your case your Firewall mayblock outgoing TCP-Port 20029 I refer to the refuse Error.

Can you explain? Is that IP then visible in the admin tool or not?
If the bot uses proxy to login and everything else then we should be fine?

**Comment by alaingilbert** [comment]
They don't see the IP of the websocket in their tool.

**Comment by twdnhfr** [comment]
Thanks for the replies, I am not using a proxy atm and this happened while runtime, so the chat connection worked before.

**Comment by 0xE232FE** [comment]
@alaingilbert I checked it with Wireshark now. Yes you are correct, the Issue #26 isn't an issue! Can you close it? I am totally confused by this guy @Kane67 . Damn it, he didn't even checked this out. It is so easy to run Wireshark and check it... and a little bit brain, @alaingilbert  is using the b.connect(...) which is using the instance of HTTP Client constructed by New(...) so everything set there is reused on any connect method, which is great! Well done @alaingilbert !!! Appreciate!!!

**Comment by alaingilbert** [comment]
lol the 10min auto soft-ban was quite surprising to me. It took me a little while to understand why suddenly nothing was working anymore.
