### ISSUE TITLE
[ogamed] address and port not changed on webview

### ISSUE THREAD

**Issue by CorentinGC** [alaingilbert/ogame#59]
Hi !

When I run the daemon with a custom port (--port) and address (-address), I can access the API, but the webview (/game/index.php) do not have correct  links. 
All the links are still 127.0.0.1:8080

**Comment by flashover** [comment]
Yes you will need to use the:
`--api-new-hostname='http://something.example.com`

It's not documented yet, sorry for that.

**Comment by CorentinGC** [comment]
Oh... I though it was for OGame specific url.. Thank you, and sorry for this no-issue
