### ISSUE TITLE
[Webproxy] Issue with "repairlayer" submit repair ships in wrecked field cause redirect

### ISSUE THREAD

**Issue by 0xE232FE** [alaingilbert/ogame#60]
There is a problem with Wrecked Fields, if you start repair fleet you get redirected to the login page.
After repair you can recommision the ships this submit doesn't cause redirect to lobby login page!

**Comment by 0xE232FE** [comment]
After repair you can recommision the ships this submit doesn't cause redirect to lobby login page!

**Comment by alaingilbert** [comment]
No longer happening ?
