### ISSUE TITLE
[webproxy] Ogame .xml API 

### ISSUE THREAD

**Issue by 0xE232FE** [alaingilbert/ogame#61]
Hello Alain,

In the Handler the XMLBlob produces an additional line at the beginning of the xml file.
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
...

If we have an XML already we should not use XMLBlob for returning here! XMLBlob is only usefull if you generate XML out of an XML structured Binaray or Text.

https://github.com/alaingilbert/ogame/blob/8e94e4e791bdf80fd8cab8291a07f127d8d8493c/handlers.go#L839

use just c.Blob(http.StatusOK, "application/xml", body)

**Comment by alaingilbert** [comment]
Fixed in 29.5.0 :)

**Comment by 0xE232FE** [comment]
Super! Thank you very much! cheers!
