### ISSUE TITLE
Page not found allianceInfo.php

### ISSUE THREAD

**Issue by CorentinGC** [alaingilbert/ogame#62]
Hi !

On the webview, alliances homepage are not accessible ( /game/allianceInfo.php?allianceId=XXX)

**Comment by 0xE232FE** [comment]
this issue is fixed already.

**Comment by CorentinGC** [comment]
In which release ? 
Because when I try to access alliance page I got this message : 
<img width="417" alt="Alliance page not found" src="https://user-images.githubusercontent.com/1381160/75552788-5f7dc300-5a37-11ea-9c3a-1c127de48ddd.png">
