### ISSUE TITLE
Send-fleet command says invalid ship id

### ISSUE THREAD

**Issue by antal-kajzer** [alaingilbert/ogame#78]
hi my friend!

I just tried to send 1 small cargo to my planet, but the command says, invalid ship id.

command: curl -X POST localhost:8080/bot/planets/33628320/send-fleet -d 'ships="202,1"&speed=10&galaxy=2&system=298&type=3&position=8&mission=4&metal=1&crystal=2&deuterium=3'

I've checked the ids at: https://github.com/alaingilbert/ogame/blob/3a49d038b5a020622f80821dcf050bd71747f7b9/constants.go#L152

Could you please help me about that?

**Comment by alaingilbert** [comment]
I think the double quotes are causing the issue. There should be no `"`

**Comment by antal-kajzer** [comment]
Ahh, yes. That caused the issue, thank you!
In this case, could you please fix the comment at https://github.com/alaingilbert/ogame/blob/52ac62216be3cfb31f97a71986b46776f8f2a2fa/handlers.go#L757?

**Comment by antal-kajzer** [comment]
The issue was: Incorrect command parameter format
