### ISSUE TITLE
Strong player detection broken

### ISSUE THREAD

**Issue by elnappo** [alaingilbert/ogame#83]
Seams like the strong player detection is broken as every active player gets reported as "strong". If I inspect the HTML of the game, it looks like every active player has the class "strong_filter". 

If I understand it correctly, this change should fix it:
```go
planetInfos.StrongPlayer = strings.Contains(classes, "strong_filter")
planetInfos.StrongPlayer = s.Find("span.status_abbr_strong").Size() > 0
```
Is my understanding correct?

**Comment by alaingilbert** [comment]
Yeah, the "strong player detection" seems to not be working as expected.
Thanks for the fix, I'll check it out.
