### ISSUE TITLE
Get ship and defense build queue on planet

### ISSUE THREAD

**Issue by elnappo** [alaingilbert/ogame#88]
It would be nice if one could access the ship and defense build queue on a given planet. This would allow to e.g., check if a certain amount of ships is already in the build queue and not add even more ships to the queue falsely.

**Comment by alaingilbert** [comment]
This function does it https://github.com/alaingilbert/ogame/blob/e466844dcd01715f10809a92ba740190bc60e7de/ogame.go#L4589
