### ISSUE TITLE
Get all planets of a player

### ISSUE THREAD

**Issue by elnappo** [alaingilbert/ogame#93]
Is there a way to get all planets of a given player? If not, how could this be implemented? Some browser extensions are able to show you all planets and moons of a player.

**Comment by flashover** [comment]
Hi

Yes you can use this: https://gist.github.com/psmolak/409d038fb4a9157aecf25c84110d5b55

So you can grab the `universe.xml` and `players.xml` and combine the data based on `PlayerID`.

Cheers

**Comment by flashover** [comment]
Or you can use:

`http://server/api/playerData.xml?id=$id`
